_target_: src.models.koopman.Koopman
_recursive_: true
name: koopman
model_obj:
  _target_: src.models.model_objs.model_objs.FullyConnectedMse
  x_dim: ${dataset.x_dim}
  num_freqs: 8
  n: 128
sample_num: 12
weight_decay: 0.00
lr_theta: 3e-3
lr_omega: 1e-7
verbose: true
hard_code_periods:
iterations: 500