_target_: src.models.koopman_probabilistic.KoopmanProb
_recursive_: true

name: prob_koopman

model_obj:
  _target_: src.models.model_objs.prob_model_objs.NormalNLL
  x_dim: ${dataset.x_dim}
  num_freqs:
    - 8
    - 3
  n: 512
  n2: 128
sample_num: 12
seed: ${seed}
weight_decay: 0.001
lr_theta: 3e-3
lr_omega: 1e-7
verbose: true
hard_code_periods:
iterations: 400