defaults:
  - _self_
  - user_settings: user_settings
  - model: fourier
  - dataset: navier_stokes

render_path: ${user_settings.project_path}/render
save_path: ${user_settings.project_path}/plots
datasets_root: ${user_settings.datasets_root}
#
T: 1000.0
delta_t: 1

y_window: 10

seed: 321

plot: True
sample_plot:
