defaults:
  - _self_
  - user_settings: user_settings
  - model: coord_prob_koopman
  - dataset: navier_stokes

results_dir: ${user_settings.hydra_dir}
render_path: ${user_settings.project_path}/render
save_path: ${user_settings.results_dir}/plots
eval_save_path: ${results_dir}/stats.csv
datasets_root: ${user_settings.datasets_root}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}
hydra:
  run:
    dir: ${hydra_dir}
#
T: 300
delta_t: 0.1

y_window: 300

seed: 321

plotting:
  plot: True
  n_plots: 10
  render: false
  save:
    dir: ${user_settings.project_path}/plots
