defaults:
  - _self_
  - user_settings: user_settings
  - model: DMD
  - dataset: navier_stokes

render_path: ${user_settings.project_path}/render
save_path: ${user_settings.project_path}/plots
datasets_root: ${user_settings.datasets_root}
#
T: 10.0
delta_t: 0.1

y_window: 300

seed: 321

plot: True
