defaults:
  - _self_
  - user_settings: user_settings

project_path: ${user_settings.project_path}
datasets_root: ${user_settings.datasets_root}
results_dir: ${user_settings.results_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}
hydra:
  run:
    dir:
      ${hydra_dir}

config_file: "config.yaml"
metrics_file: "stats.csv"

experiments_plots_dir: "experiments_plots"
evaluation_dirs:
