_target_: src.data_loaders.navier_stokes.NSLoader
name: navier_stokes

T: ${T}
ds: ${delta_t}

seed: ${seed}

domain_params:
  _target_: src.data_loaders.navier_stokes.DomainParams
  nu: 1e-3  # 1/Re or viscosity

  # Domain definition
  Lx: numpy.pi  # Domain half-length in x-direction
  Ly: numpy.pi  # Domain half-length in y-direction

  # Numerical parameters
  Nx: 512  # number of Fourier modes in discrete solution x-dir
  Ny: 512  # number of Fourier modes in discrete solution y-dir

x_dim: 30
sample: 30

save_params:
  _target_: src.data_loaders.navier_stokes.SaveParams
  dir: ${datasets_root}/${dataset.name}
  data_path: ${dataset.save_params.dir}/ts_4.npy
  render: ${render_path}
  render_name: 'ns_view'

init_cond:
  _target_: src.data_loaders.navier_stokes.init_cond
  Nx: ${dataset.domain_params.Nx}
  Ny: ${dataset.domain_params.Ny}

#plot: False
